# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-07 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('comment', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('is_bander', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banding_year', models.IntegerField()),
                ('metal_ring', models.CharField(max_length=20)),
                ('code', models.IntegerField()),
                ('color', models.CharField(choices=[(1, 'Red'), (2, 'White'), (3, 'Yellow'), (4, 'Green')], max_length=20)),
                ('sex', models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Undetermined')], max_length=20)),
                ('age', models.CharField(max_length=5)),
                ('banding_date', models.DateField()),
                ('bading_time', models.TimeField()),
                ('bander', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plovers', to='core.Observer')),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='observer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.Observer'),
        ),
        migrations.AddField(
            model_name='observation',
            name='plover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.Plover'),
        ),
    ]
