# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-07 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plover',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plovers', to='core.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='locality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plover',
            name='bading_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='plover',
            name='metal_ring',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
