# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-07 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170207_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plover',
            old_name='bading_time',
            new_name='banding_time',
        ),
    ]
