# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-09 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170207_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='x_coordinate',
            new_name='coordinate_x',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='y_coordinate',
            new_name='coordinate_y',
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plover',
            name='bander',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plovers', to='core.Observer'),
        ),
        migrations.AlterField(
            model_name='plover',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plovers', to='core.Location'),
        ),
    ]
