# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-09 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170209_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locality',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
