# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-09 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170308_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='supposed_sex',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Undetermined')], default=2, max_length=20),
        ),
        migrations.AlterField(
            model_name='plover',
            name='color',
            field=models.CharField(choices=[(0, 'Red'), (1, 'White'), (2, 'Yellow'), (3, 'Green')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='plover',
            name='sex',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Undetermined')], default=2, max_length=20),
        ),
    ]
