# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170309_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='core.Observer'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='supposed_sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undetermined')], default=2, max_length=20),
        ),
        migrations.AlterField(
            model_name='plover',
            name='bander',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plovers', to='core.Observer'),
        ),
        migrations.AlterField(
            model_name='plover',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('W', 'White'), ('Y', 'Yellow'), ('G', 'Green')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='plover',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plovers', to='core.Location'),
        ),
        migrations.AlterField(
            model_name='plover',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undetermined')], default=2, max_length=20),
        ),
    ]
