# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170310_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plover',
            name='banding_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Banding time'),
        ),
        migrations.AlterField(
            model_name='plover',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('P', 'Pink'), ('W', 'White'), ('Y', 'Yellow'), ('G', 'Green')], default=0, max_length=20, verbose_name='Color'),
        ),
    ]
