# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170319_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plover',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('P', 'Pink'), ('W', 'White'), ('Y', 'Yellow'), ('G', 'Green')], default=0, max_length=1, verbose_name='Color'),
        ),
    ]
