# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170309_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-date'], 'verbose_name': 'Observation', 'verbose_name_plural': 'Observations'},
        ),
        migrations.AlterModelOptions(
            name='observer',
            options={'verbose_name': 'Observer', 'verbose_name_plural': 'Observers'},
        ),
        migrations.AlterModelOptions(
            name='plover',
            options={'verbose_name': 'Kentish plover', 'verbose_name_plural': 'Kentish plovers'},
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='department',
            field=models.CharField(max_length=255, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='location',
            name='locality',
            field=models.CharField(max_length=255, null=True, verbose_name='Locality'),
        ),
        migrations.AlterField(
            model_name='location',
            name='town',
            field=models.CharField(max_length=255, verbose_name='Town'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='comment',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='coordinate_x',
            field=models.FloatField(null=True, verbose_name='X coordinate'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='coordinate_y',
            field=models.FloatField(null=True, verbose_name='Y coordinate'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='core.Observer', verbose_name='Observer'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='plover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.Plover', verbose_name='Plover'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='supposed_sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undetermined')], default=2, max_length=20, verbose_name='Supposed Sex'),
        ),
        migrations.AlterField(
            model_name='observer',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='observer',
            name='is_bander',
            field=models.BooleanField(default=False, verbose_name='Is bander'),
        ),
        migrations.AlterField(
            model_name='observer',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='plover',
            name='age',
            field=models.CharField(max_length=5, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='plover',
            name='bander',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plovers', to='core.Observer', verbose_name='Bander'),
        ),
        migrations.AlterField(
            model_name='plover',
            name='banding_date',
            field=models.DateField(verbose_name='Banding date'),
        ),
        migrations.AlterField(
            model_name='plover',
            name='banding_time',
            field=models.TimeField(blank=True, verbose_name='Banding time'),
        ),
        migrations.AlterField(
            model_name='plover',
            name='banding_year',
            field=models.IntegerField(verbose_name='Banding year'),
        ),
        migrations.AlterField(
            model_name='plover',
            name='code',
            field=models.IntegerField(verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='plover',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('W', 'White'), ('Y', 'Yellow'), ('G', 'Green')], default=0, max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='plover',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plovers', to='core.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='plover',
            name='metal_ring',
            field=models.CharField(max_length=20, unique=True, verbose_name='Metal ring'),
        ),
        migrations.AlterField(
            model_name='plover',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undetermined')], default=2, max_length=20, verbose_name='Sex'),
        ),
    ]
