# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170319_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='observer',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
    ]
